name: Publish Python Module to TestPyPI and PyPI

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  deploy:
    environment: publish package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel twine

    - name: Build and publish to TestPyPI
      env:
        TWINE_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
      run: |
        make test-upload

    - name: Publish to PyPI (if TestPyPI was successful)
      if: ${{ success() }}
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make publish
